services:
  m365server:
    build: 
      context: ./m365server
      dockerfile: Dockerfile
    container_name: m365-server
    ports:
      - 17200:17200
      - 5678:5678
    volumes:
      - ./m365server:/code
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - 16379:16379
    volumes:
    - ./redis.conf:/usr/local/etc/redis/redis.conf
    - /mnt/e/redis-data/hq-sync:/data:rw
    command: redis-server /usr/local/etc/redis/redis.conf
