services:
  m365server:
    build: 
      context: ./m365server
      dockerfile: Dockerfile
    container_name: m365server
    ports:
      - "${M365_SERVER_PORT}:${M365_SERVER_PORT}"
    volumes:
      - ./m365server:/code
      - ./m365server/config:/app/config
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - "${REDIS_DATA_DIR}:/data:rw"
    command: redis-server /usr/local/etc/redis/redis.conf