from m365server.azure_interface.blob_operations.interfaces import IBlobUploadStrategy, IBlobDownloadStrategy, IBlobDeleteStrategy
from m365server.azure_interface.blob_operations.upload import BlobUploadStrategy
from m365server.azure_interface.blob_operations.delete import BlobDeleteStrategy
from m365server.azure_interface.blob_operations.download import BlobDownloadStrategy